/* mode-flicker.c - random flickering of LEDs
 *
 * (c) David Haworth
 *
 *  This file is part of ledstrip85.
 *
 *  ledstrip85 is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  ledstrip85 is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with ledstrip85.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "ledstrip85.h"

/* mode_flicker() - turn each LED on or off pseudo-randomly
 *
 * The pseudo-random sequence is generated by a linear feedback shift register (LFSR).
 * Each LED has its own LFSR. The LFSRs have different lengths.
*/
void mode_flicker(void)
{
	unsigned long r;
	for (;;)
	{
		r = lfsr_r();
		pin_set(LED_R, ( ((r & 0x1) == 0) ) ? HIGH : LOW);
		r = lfsr_g();
		pin_set(LED_G, ( ((r & 0x1) == 0) ) ? HIGH : LOW);
		r = lfsr_b();
		pin_set(LED_B, ( ((r & 0x1) == 0) ) ? HIGH : LOW);
		vdelay(1000);
	}
}
